module.exports = {
  contentful: {
    repo: "https://github.com/gatsbyjs/gatsby-starter-contentful-homepage",
    cms: "Contentful",
    name: "contentful",
    dirname: "contentful-plugin",
    demoURL: "https://gatsbycontentfulhomepage.gatsbyjs.io/",
    deploynow:
      "https://www.gatsbyjs.com/dashboard/deploynow?url=https://github.com/gatsbyjs/gatsby-starter-contentful-homepage",
    isTypescript: false,
  },
  // "contentful-ts": {
  //   repo: "",
  //   cms: "Contentful",
  //   name: "contentful",
  //   dirname: "contentful-plugin",
  //   demoURL: "",
  //   deploynow: "",
  //   isTypescript: true,
  // },
  datocms: {
    repo: "https://github.com/gatsbyjs/gatsby-starter-datocms-homepage",
    cms: "DatoCMS",
    name: "datocms",
    dirname: "datocms-plugin",
    demoURL: "https://gatsbydatocmshomepage.gatsbyjs.io/",
    deploynow:
      "https://www.gatsbyjs.com/dashboard/deploynow?url=https://github.com/gatsbyjs/gatsby-starter-datocms-homepage",
    isTypescript: false,
  },
  // "datocms-ts": {
  //   repo: "",
  //   cms: "DatoCMS",
  //   name: "datocms",
  //   dirname: "datocms-plugin",
  //   demoURL: "",
  //   deploynow: "",
  //   isTypescript: true,
  // },
  drupal: {
    repo: "https://github.com/gatsbyjs/gatsby-starter-drupal-homepage",
    cms: "Drupal",
    name: "drupal",
    dirname: "drupal-plugin",
    demoURL: "https://gatsbydrupalhomepage.gatsbyjs.io/",
    deploynow:
      "https://www.gatsbyjs.com/dashboard/deploynow?url=https://github.com/gatsbyjs/gatsby-starter-drupal-homepage",
    isTypescript: false,
  },
  // "drupal-ts": {
  //   repo: "",
  //   cms: "Drupal",
  //   name: "drupal",
  //   dirname: "drupal-plugin",
  //   demoURL: "",
  //   deploynow: "",
  //   isTypescript: true,
  // },
  wordpress: {
    repo: "https://github.com/gatsbyjs/gatsby-starter-wordpress-homepage",
    cms: "WordPress",
    name: "wordpress",
    dirname: "wordpress-plugin",
    demoURL: "https://gatsbywordpresshomepage.gatsbyjs.io/",
    deploynow:
      "https://www.gatsbyjs.com/dashboard/deploynow?url=https://github.com/gatsbyjs/gatsby-starter-wordpress-homepage",
    isTypescript: false,
  },
  // "wordpress-ts": {
  //   repo: "",
  //   cms: "WordPress",
  //   name: "wordpress",
  //   dirname: "wordpress-plugin",
  //   demoURL: "",
  //   deploynow: "",
  //   isTypescript: true,
  // },
}
